### ISSUE TITLE
Issue executing the script

### ISSUE THREAD

**Issue by ukamath** [kimber-chen/Twitter-stance-classification-by-TensorFlow#1]
Hello

Parameters:
ALLOW_SOFT_PLACEMENT=True
BATCH_SIZE=16
DROPOUT_KEEP_PROB=0.5
EMBEDDING_DIM=128
EVALUATE_EVERY=100
FILTER_SIZES=3,4,5
L2_REG_LAMBDA=0.0
LOG_DEVICE_PLACEMENT=False
NUM_EPOCHS=500
NUM_FILTERS=128
STOP_STEP=1500
TASK=taskA
TESTING_FILE=traindev/rumoureval-subtaskA-dev.json
TRAINING_FILE=traindev/rumoureval-subtaskA-train.json

Loading data...
Traceback (most recent call last):
  File "./train.py", line 55, in <module>
    x_train, y_train,trainID = data_helpers.load_data_and_labels(task,training_file)
  File "/Users/X/Twitter-stance-classification-by-TensorFlow-master/CNN_word embedding/data_helpers.py", line 72, in load_data_and_labels
    if(match_text(id)):
  File "/Users/X/Twitter-stance-classification-by-TensorFlow-master/CNN_word embedding/data_helpers.py", line 36, in match_text
    if ID in listdir(mypath+d):
NotADirectoryError: [Errno 20] Not a directory: 'rumoureval-data/.DS_Store'

I downloaded the zip from Pheme and exploded it in the rumoreval-data?  What else is needed ?
Thanks

**Comment by ukamath** [comment]
Resolved by removing all .DS_Store files
